# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yo5hX2Hq6PHWY9TL5OfO8TK--kFxh1aH
"""

from setuptools import setup, find_packages

setup(
    name=‘DS’,
    version='0.1',
    packages=find_packages(),
    install_requires=[
        # List your dependencies here
    ],
)